name: Setup DVC
author: Iterative, Inc.
description: An action to automatically setup DVC
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down'
  color: 'green'
inputs:
  version:
    description: The version of DVC to install
    required: false
    default: 'latest'
